services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ks
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - ./.data/db:/var/lib/postgresql/data
